name: Mutation testing pull request workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute pitest
        uses: isamadrid90/gradle-pitest-comment-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reports-retention: 1
